---
- name: "Install fish plugins"
  ansible.builtin.shell: "fisher install {{ item }}"
  when:
    - __fish_is_installed
    - __fisher_is_installed
    - item not in __fisher_installed_plugins
  args:
    executable: "{{ __fish_binary_path }}"
  loop: "{{ fisher_plugins }}"
  register: __fish_plugins_install_rg

- name: "Update installed plugins list fact"
  ansible.builtin.set_fact:
    __fisher_installed_plugins: "{{ (__fisher_installed_plugins + (fisher_plugins | intersect(ansible_loop_results))) | unique }}"
  vars:
    ansible_loop_results: "{{ __fish_plugins_install_rg.results | select('succeeded') | map(attribute='item') | list }}"
  when: __fish_plugins_install_rg is changed
