---
- name: "Install fisher"
  when:
    - __fish_is_installed
    - not __fisher_is_installed
  block:
    - name: "Download fisher install script"
      ansible.builtin.get_url:
        url: "{{ fisher_url }}"
        dest: "/tmp/fisher.fish"
        mode: '0777'

    - name: "Install fisher"
      ansible.builtin.shell: |
        source /tmp/fisher.fish &&
        fisher install {{ fisher_package_name }}
      args:
        executable: "{{ __fish_binary_path }}"
      register: __fisher_install_res
      changed_when: true

    - name: "Update fisher fact after install"
      ansible.builtin.set_fact:
        __fisher_is_installed: true
      when: __fisher_install_res is succeeded

  always:
    - name: "Remove temporary fisher script"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "/tmp/fisher.fish"
        state: absent
      changed_when: false
