---
# defaults file for fish

fish_key_id: "24A63B31CAB41B33EC48801E2CE2AC08D880C8E4"
fish_key_url: "https://download.opensuse.org/repositories/shells:fish:release:4/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}/Release.key"
fish_key_path: "/etc/apt/trusted.gpg.d/shells_fish_release_4.gpg"

fish_package_version: "4.5.0-1"
fish_repo_url: "https://download.opensuse.org/repositories/shells:/fish:/release:/4/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}/"

fisher: true
fisher_package_name: "jorgebucaran/fisher"
fisher_url: "https://raw.githubusercontent.com/jorgebucaran/fisher/a04308be92daa6cfecdbb0ca58b1e8508664cff2/functions/fisher.fish"
fisher_install_plugins: true
fisher_plugins: []
