---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  # Debian 13 - Trixie
  - name: role-git_debian13_${MOLECULE_INSTANCE_ID}
    image: "python:3.13.12-trixie"
    pre_build_image: true

  # Debian 12 - Bookworm
  - name: role-git_debian12_${MOLECULE_INSTANCE_ID}
    image: "python:3.13.12-bookworm"
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"
  inventory:
    group_vars:
      all:
        git_user_name: "Foo Bar"
        git_user_email: "foo@bar.com"
        git_user_signingkey: "1234"
        git_commit_gpgsign: "true"
        git_tag_gpgsign: "false"

verifier:
  name: testinfra
