---
- name: "Get __broot_is_installed"
  block:
    - name: "Get current broot version"
      ansible.builtin.command: "/usr/local/bin/broot --version"
      register: __broot_version_check
      changed_when: false
      failed_when: false

    - name: "Set facts for version comparison"
      ansible.builtin.set_fact:
        __broot_is_installed: >-
          {{
            __broot_version_check.rc == 0 and
            broot_package_version in __broot_version_check.stdout
          }}
