---
# vars file for tmux

__tmux_build_dependencies:
  - libevent-dev
  - libncurses-dev
  - gcc
  - make
  - pkg-config
  - bison

__tmux_tar_filename: "tmux-{{ tmux_version }}.tar.gz"
__tmux_src_dir: "/tmp/tmux-{{ tmux_version }}"
__tmux_install_path: "/usr/local/bin/tmux"
