---
- name: "Install mise"
  when: not __mise_is_installed
  block:
    - name: "Install from install.sh"
      block:
        - name: "Create tmp dir"
          become: true
          become_user: root
          ansible.builtin.file:
            path: "/tmp/mise"
            state: directory

        - name: "Import GPG key"
          become: true
          become_user: root
          ansible.builtin.command:
            cmd: "gpg --keyserver hkps://keys.openpgp.org --recv-keys {{ mise_key }}"
          changed_when: false

        - name: "Download and verify install script"
          become: true
          become_user: root
          ansible.builtin.shell:
            cmd: "curl -fsSL {{ mise_package_url }} | gpg --decrypt > /tmp/mise/install.sh"
          changed_when: false

        - name: "Run install.sh"
          become: true
          become_user: root
          ansible.builtin.command:
            cmd: "sh /tmp/mise/install.sh"
          environment:
            MISE_VERSION: "v{{ mise_package_version }}"
            MISE_INSTALL_PATH: "/usr/local/bin/mise"
          changed_when: true

  always:
    - name: "Remove tmp files"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "/tmp/mise"
        state: absent
