---
- name: "Get __btop_is_installed"
  block:
    - name: "Get current btop version"
      ansible.builtin.command: "btop --version"
      register: __btop_version_check
      changed_when: false
      failed_when: false

    - name: "Set facts for version comparison"
      ansible.builtin.set_fact:
        __btop_is_installed: >-
          {{
            __btop_version_check.rc == 0 and
            btop_package_version in __btop_version_check.stdout
          }}
